config/routes.rb
Rails.application.routes.draw do
  resources :line_items
  resources :carts
  resources :instruments
  devise_for :users, controllers: {
    registrations: 'registrations'
  }
  root 'instruments#main'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :line_items, dependent: :destroy

  def add_instrument(instrument)
    current_item = line_items.find_by(instrument_id: instrument.id)
    if current_item
      current_item.increment(:quantity)
    else
      current_item = line_items.build(instrument_id: instrument.id)
    end
    current_item
  end

  def total_price
    line_items.to_a.sum { |item| item.total_price }
  end
end

app/models/concerns/current_cart.rb
module CurrentCart
  
  private

  def set_cart
    @cart = Cart.find(session[:cart_id])
  rescue ActiveRecord::RecordNotFound
    @cart = Cart.create
    session[:cart_id] = @cart.id
  end
end

app/models/instrument.rb
class Instrument < ApplicationRecord
  before_destroy :not_referenced_by_any_line_item
  has_many :line_item
  mount_uploader :image, ImageUploader
  serialize :image, JSON
  belongs_to :user, optional: true
  validates :title, :brand, :price, :model, presence: true
  validates :description, length: { maximum: 1000, too_long: "%{count} characters is the maximum aloud."}
  validates :title, length: {maximum: 140, too_long: "%{count} characters is the maximum aloud."}
  validates :price, length: { maximum: 7 }
  
  BRAND = %w{ Fender Gibson Epiphone ESP Martin Dean Taylor Jackson PRS  Ibanez Charvel Washburn }
  FINISH = %w{ Black White Navy Blue Red Clear Satin Yellow Seafoam }
  CONDITION = %w{ New Excellent Mint Used Fair Poor }

  private

  def not_referenced_by_any_line_item
    unless line_item.empty?
      errors.add(:base, 'Line items present')
      throw :abort
    end
  end
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :instrument
  belongs_to :cart

  def total_price
    instrument.price.to_i * quantity.to_i
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :instruments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include CurrentCart
  before_action :set_cart 
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  rescue_from ActiveRecord::RecordNotFound, with: :invalid_cart
  before_action :set_cart, only: %i[ show edit update destroy ]

  def index
    @carts = Cart.all
  end

  def show
  end

  def new
    @cart = Cart.new
  end

  def edit
  end

  def create
    @cart = Cart.new(cart_params)
    if @cart.save
      redirect_to cart_url(@cart), notice: "Cart was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @cart.update(cart_params)
      redirect_to cart_url(@cart), notice: "Cart was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @cart.destroy if @cart.id == session[:cart_id]
    session[:cart_id] = nil

    format.html { redirect_to root_path, notice: "Cart was successfully destroyed." }
  end

  private
    def set_cart
      @cart = Cart.find(params[:id])
    end

    def cart_params
      params.fetch(:cart, {})
    end

    def invalid_cart
      logger.error "Attempt to access invalid cart #{params[:id]}"
      redirect_to root_path, notice: "That cart doesn't exist"
    end
end

app/controllers/instruments_controller.rb
class InstrumentsController < ApplicationController
  before_action :set_instrument, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show, :main]

  def main
    @instruments = Instrument.all
  end

  def index
    @instruments = Instrument.all.order('created_at desc')
  end

  def show
    @instruments = Instrument.all
  end

  def new
    @instrument = current_user.instruments.build
  end

  def edit
  end

  def create
    @instrument = current_user.instruments.build(instrument_params)
    if @instrument.save
      redirect_to instrument_url(@instrument), notice: "Instrument was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @instrument.update(instrument_params)
      redirect_to instrument_url(@instrument), notice: "Instrument was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @instrument.destroy
    redirect_to instruments_url, notice: "Instrument was successfully destroyed."
  end

  private
    def set_instrument
      @instrument = Instrument.find(params[:id])
    end

    def instrument_params
      params.require(:instrument).permit(:brand, :model, :description, :condition, :finish, :title, :price, :image)
    end
end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController
  include CurrentCart
  before_action :set_line_item, only: %i[ show edit update destroy ]
  before_action :set_cart, only: [:create]

  def index
    @line_items = LineItem.all
  end

  def show
  end

  def new
    @line_item = LineItem.new
  end

  def edit
  end

  def create
    instrument = Instrument.find(params[:instrument_id])
    @line_item = @cart.add_instrument(instrument)
    if @line_item.save
      redirect_to @line_item.cart, notice: "Item added to cart."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @line_item.update(line_item_params)
      redirect_to line_item_url(@line_item), notice: "Line item was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @cart = Cart.find(session[:cart_id])
    @line_item.destroy
    redirect_to cart_path(@cart), notice: "Line item was successfully destroyed."
  end

  private
    def set_line_item
      @line_item = LineItem.find(params[:id])
    end

    def line_item_params
      params.require(:line_item).permit(:instrument_id, :cart_id)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  

  private

  def sign_up_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :current_password)
  end
end

app/controllers/store_controller.rb
class StoreController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def cart_count_over_one
    if @cart.line_items.count > 0
      return "<span class='btn btn-dark py-1'>#{@cart.line_items.count}</span>".html_safe
    end
  end

  def cart_has_items
    return @cart.line_items.count > 0
  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/instruments_helper.rb
module InstrumentsHelper
  def instrument_author(instrument)

    user_signed_in? && current_user.id == instrument.user_id
    
  end
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/views/carts/_form.html.slim
= simple_form_for(@cart) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs

  .form-actions
    = f.button :submit

app/views/carts/edit.html.slim
h1 Editing cart

== render 'form'

=> link_to 'Show', @cart
'|
=< link_to 'Back', carts_path

app/views/carts/index.html.slim
h1 Listing carts

table
  thead
    tr
      th
      th
      th

  tbody
    - @carts.each do |cart|
      tr
        td = link_to 'Show', cart
        td = link_to 'Edit', edit_cart_path(cart)
        td = link_to 'Destroy', cart, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Cart', new_cart_path

app/views/carts/new.html.slim
h1 New cart

== render 'form'

= link_to 'Back', carts_path

app/views/carts/show.html.slim
.keep-shopping.text-end.my-3
  = link_to 'Keep Shopping', instruments_path, class: 'btn btn-warning'
section.section.border-top
  
  = render(@cart.line_items)
  
  .row.border-top.mt-3
    .col.mt-1
      = button_to 'Empty Cart', @cart, method: :delete, data: { confirm: "Are you sure?"}, class: 'btn btn-danger'
    .col.total.mt-3
      h4.title.text-end
        span Total: 
        = number_to_currency(@cart.total_price)

app/views/instruments/_form.html.slim
= simple_form_for(@instrument, html: { multipart: true }) do |f|
  = f.error_notification

  .form-inputs
    .row
      .col
        = f.input :title, required: true, input_html: { class: 'form-control' }, label_html: { class: 'label' }
      .col
        = f.input :price, required: true, input_html: { class: 'form-control', maxlength: 7 }, label_html: { class: 'label' }
    = f.input :model, required: true, input_html: { class: 'form-control' }, label_html: { class: 'label' }
    = f.input :description, required: true, input_html: { class: 'form-control' }, label_html: { class:"label" }
    .row.my-3
      .col
        = f.input :brand, collection: Instrument::BRAND, prompt: 'Select brand', input_html: { class: 'form-select' }
      .col
        = f.input :finish, collection: Instrument::FINISH, prompt: 'Select finish', input_html: { class: 'form-select' }
      .col
        = f.input :condition, collection: Instrument::CONDITION, prompt: 'Select condition', input_html: { class: 'form-select' }
    = f.input :image, as: :file, input_html: { class:'file-input instrument-image form-control my-1' }, label: 'Add Image'
  .form-actions
    = f.button :submit, class: 'btn btn-warning my-3'

app/views/instruments/edit.html.slim
h1 Editing instrument

== render 'form'

=> link_to 'Show', @instrument
'|
=< link_to 'Back', instruments_path

app/views/instruments/index.html.slim
- content_for :header do
  section.hero.is-warning 
    .hero-body
      .container
        h1.title
          | Browse the latest instruments on Flanger

.instrument-index-grid
  - @instruments.each do |instrument|
    .instrument.border.bg-light
      .instrument-thumb
        = link_to image_tag(instrument.image_url(:thumb)), instrument
        - if instrument.condition?
          .condition
            span.tag.btn.btn-secondary
              = instrument.condition

      h3.title
        = link_to instrument.title, instrument, class: 'text-decoration-none m-2'
      .text-center.my-3
        p.d-inline.fst-italic Sold by: 
        .fw-bold.d-inline
          = instrument.user.name
      p.price.fw-bold
        = number_to_currency(instrument.price)
      .text-center
        - if instrument_author(instrument)
          = link_to 'Edit', edit_instrument_path(instrument), class: 'btn btn-success me-1'
          = link_to 'Delete', instrument, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger'

app/views/instruments/main.html.slim
/ Header image
.header.d-flex.align-items-center.justify-content-center.flex-column
  h1.header-title.text-center
    | SHOP ALL INSTRUMENTS
  p.header-subtitle
    | Shop all the collection.
  = link_to 'SHOP NOW', instruments_path, class: 'btn btn-main btn-black btn-large'

/ Featured Clothing
.featured-clothing
  h1.text-center.mt-5.pt-5.pb-5.featured-clothing-text
    | Featured Clothing
  .container.featured-clothing-item
    .row
      .col-md-4
        .featured-clothing-item-img
          = link_to image_tag(@instruments.first.image_url(:default)), @instruments.first
        .featured-clothing-item-title
          = link_to @instruments.first.title, @instruments.first
        .featured-clothing-item-price
          = number_to_currency(@instruments.first.price)
      .col-md-4
        .featured-clothing-item-img
          = link_to image_tag(@instruments.second.image_url(:default)), @instruments.second
        .featured-clothing-item-title
          = link_to @instruments.second.title, @instruments.second
        .featured-clothing-item-price
          = number_to_currency(@instruments.second.price)
      .col-md-4
        .featured-clothing-item-img
          = link_to image_tag(@instruments.third.image_url(:default)), @instruments.third
        .featured-clothing-item-title
          = link_to @instruments.third.title, @instruments.third
        .featured-clothing-item-price
          = number_to_currency(@instruments.third.price)

/ Categories grid
.category-grid.container
  .row.pb-3.d-flex.justify-content-center
    .category.col-md-6.position-relative.m-3
      = link_to image_tag('cate1.jpg'), instruments_path
      = link_to 'SHOP NOW', instruments_path, class: 'btn position-absolute bottom-0 start-0 btn-main category-btn'
      h2.category-title.category-title.position-absolute.bottom-0.start-0.text-dark.bg-light
        | Hoodies
    .category.col-md-6.position-relative.m-3
      = link_to image_tag('cate2.jpg'), instruments_path
      = link_to 'SHOP NOW', instruments_path, class: 'btn position-absolute bottom-0 start-0 btn-main category-btn'
      h2.category-title.position-absolute.bottom-0.start-0.text-dark.bg-light
        | T-Shirts
    .category.col-md-6.position-relative.m-3
      = link_to image_tag('cate3.jpg'), instruments_path
      = link_to 'SHOP NOW', instruments_path, class: 'btn position-absolute bottom-0 start-0 btn-main category-btn'
      h2.category-title.position-absolute.bottom-0.start-0.text-dark.bg-light
        | Ruby
    .category.col-md-6.position-relative.m-3
      = link_to image_tag('cate4.jpg'), instruments_path
      = link_to 'SHOP NOW', instruments_path, class: 'btn position-absolute bottom-0 start-0 btn-main category-btn'
      h2.category-title.position-absolute.bottom-0.start-0.text-dark.bg-light
        | Solidus

/ Featured accessories
.featured-accessories
  h1.featured-accessories-text.text-center
    | Featured Accessories
  .row.d-flex.justify-content-center
    .featured-accessories-item.col-md-3
      .featured-accessories-img
        = link_to image_tag(@instruments.first.image_url(:default), class: 'test-class'), @instruments.first
      .featured-accessories-title
        = link_to @instruments.first.title, @instruments.first
      .featured-accessories-price
        = number_to_currency(@instruments.first.price)
    .featured-accessories-item.col-md-3
      .featured-accessories-img
        = link_to image_tag(@instruments.third.image_url(:default)), @instruments.third
      .featured-accessories-title
        = link_to @instruments.third.title, @instruments.third
      .featured-accessories-price
        = number_to_currency(@instruments.third.price)
/ Reusable Water Bottles
.reusable-bottles
  .row
    .col-md-6.offset-md-6
      .reusable-bottles-group-text
        h1
          | Reusable Water Bottles
        p
          | Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
        .reusable-bottles-btn
        = link_to 'SHOP NOW', instruments_path, class: 'btn btn-main btn-black btn-large'

/ We Are Minimalist
.we-are-minimalist.container
  .row
    .we-are-minimalist-img.col-md-6
      = image_tag('audience.jpg')
    .we-are-minimalist-text.col-md-6.d-flex.flex-column.align-self-center
      h1
        | We are Minimalist
      p
        | Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas feugiat mattis augue, vitae consectetur felis varius nec. Nam lobortis semper volutpat.
      p
        | Suspendisse libero metus, commodo et nisl ac, lobortis fringilla quam.

/ More Instruments
.more-instruments.container
  .row
    - @instruments.each do |instrument|
      .more-instruments-item.col-md-4.mb-5
        .more-instruments-img
          = link_to image_tag(instrument.image_url(:default)), instrument
        .more-instruments-title
          = link_to instrument.title, instrument
        .more-instruments-price
          = number_to_currency(instrument.price)

app/views/instruments/new.html.slim
.px-5
  h1 New instrument

  == render 'form'

  = link_to 'Back', instruments_path

app/views/instruments/show.html.slim
.instrument-show.container
  .row.pt-5.mt-4
    .instrument-img.col-md-7.d-flex.justify-content-end
      = image_tag(@instrument.image_url(:default))
    .instrument-info.col-md-5.ps-4
      .instrument-title
        = @instrument.title
      .instrument-price
        = number_to_currency(@instrument.price)
      .instrument-solder
        p.sold-by.d-inline Sold by: 
        .fw-bold.d-inline
          = @instrument.user.name
      = button_to 'Add To Cart', line_items_path(instrument_id: @instrument), class: 'btn btn-atc'
      - if instrument_author(@instrument)
        = link_to 'Edit', edit_instrument_path(@instrument), class: 'btn btn-edit mt-2' 

  .row.pt-5.mt-4.pb-5
    .col-md-7
      p.instrument-description-header Description
      .instrument-description 
        = @instrument.description
    .col-md-5.ps-4
      p.instrument-specs-header Product Specs
      .instrument-specs
        table.table.table-borderless.table-sm
          - if @instrument.condition
            tr
              td.left-col
                | Condition
              td.right-col
                = @instrument.condition

          - if @instrument.finish
            tr
              td.left-col
                | Finish
              td.right-col
                = @instrument.finish

          - if @instrument.brand
            tr
              td.left-col
                | Brand 
              td.right-col
                = @instrument.brand

          tr 
            td.left-col
              | Model
            td.right-col
              = @instrument.model

  .suggestion-header.pt-5.mt-4.pb-4
    p You May Also Like 
  .row.pb-5
    - @instruments.sample(3).each do |instrument|
      .suggestion-instrument.col-md-4
        .suggestion-instrument-img
          = link_to image_tag(instrument.image_url(:default)), instrument
        .suggestion-instrument-title
          = link_to instrument.title, instrument
        .suggestion-instrument-price
          = number_to_currency(instrument.price)

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Flanger</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if flash[:notice] %>
      <div class="notification bg-success global-notification">
        <p class="notice"><%= notice %></p>
      </div>
    <% end %>
    <% if flash[:alert] %>
    <div class="notification bg-danger global-notification">
      <p class="alert"><%= alert %></p>
    </div>
    <% end %>

    <nav class="navbar navbar-expand-lg navbar-light bg-white border-bottom">
      <div class="container-fluid">

        <%= link_to root_path, class: "navbar-item" do %>
          <h1 class="navbar-brand m-0">Flanger</h1>
        <% end  %>


        <div class='d-flex flex-row align-items-center'>
          <form class="d-flex align-items-center">
            <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
            <a href="#" class='me-3'>
              <i class="fa fa-search"></i>
            </a>
          </form>

          <% if cart_has_items %>
            <%= link_to cart_path(@cart), class:"navbar-item btn btn-light me-3" do %>
            <span class="icon">
              <i class="fa fa-shopping-cart"></i>
            </span>
            <span>Cart
              <%= cart_count_over_one %>
              </span>
            <% end %>
          <% end %>

          <% if user_signed_in? %>
            <%= link_to 'Sell', new_instrument_path, class: "navbar-item button is-dark" %>

            <div class="navbar-item dropdown">

              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Account
              </a>

              <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                <li class="dropdown-item">
                  <%= link_to current_user.name, edit_user_registration_path, class:"navbar-item" %>
                </li>
                <li class="dropdown-item">
                  <%= link_to "Log Out", destroy_user_session_path, method: :delete, class:"navbar-item" %>
                </li>
              </ul>

            </div>

          <% else %>
            <%= link_to "Sign In", new_user_session_path, class:"navbar-item mx-3"%>
            <%= link_to "Sign up", new_user_registration_path, class:"navbar-item mx-3"%>
          <% end %>

          
        </div>

      </div>
    </nav>

  <%= yield(:header) %>

  <div>

    <%= yield %>

  </div>
  <div class="footer">
    <div class="container">
      <h1 class="pt-5">
        <%= link_to 'Flanger', root_path, class: 'footer-brand' %>
      </h1>
      <div class="footer-link-group pt-5 pb-3">
        <a class="footer-link" href="#">
          Guides
        </a><a class="footer-link" href="#">
          Features
        </a><a class="footer-link" href="#">
          Integrations
        </a><a class="footer-link" href="#">
          Contact
        </a></div>
      <div class="powered d-flex flex-row align-items-center justify-content-center">
        <p class="m-0 pe-1 powered-by">
          Powered by
        </p>
        <a class="footer-link flanger" href="#">
          Flanger
        </a></div>
    </div>
  </div>
  </body>
</html>

app/views/line_items/_form.html.slim
= simple_form_for(@line_item) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.association :instrument
    = f.association :cart

  .form-actions
    = f.button :submit

app/views/line_items/_line_item.html.slim
  .row.align-items-center.mt-3
    .col-md-1
      = line_item.quantity
    .col-md-2
      figure.image
        = image_tag(line_item.instrument.image_url(:thumb), class:'img-fluid')
    .col-md-9 
      strong
        = line_item.instrument.title
      .row.align-items-center
        .content.col-md-9 
          = truncate(line_item.instrument.description, length: 140)
        .col-md-3.text-end
          strong
            = number_to_currency(line_item.total_price)

  .text-end 
    = link_to 'Remove Item', line_item, method: :delete, data: { confirm: "Are you sure?" }, class: 'btn btn-sm btn-secondary'

app/views/line_items/edit.html.slim
h1 Editing line_item

== render 'form'

=> link_to 'Show', @line_item
'|
=< link_to 'Back', line_items_path

app/views/line_items/index.html.slim
h1 Listing line_items

table
  thead
    tr
      th Instrument
      th Cart
      th
      th
      th

  tbody
    - @line_items.each do |line_item|
      tr
        td = line_item.instrument
        td = line_item.cart
        td = link_to 'Show', line_item
        td = link_to 'Edit', edit_line_item_path(line_item)
        td = link_to 'Destroy', line_item, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Line item', new_line_item_path

app/views/line_items/new.html.slim
h1 New line_item

== render 'form'

= link_to 'Back', line_items_path

app/views/line_items/show.html.slim
p#notice = notice

p
  strong Instrument:
  = @line_item.instrument

p
  strong Cart:
  = @line_item.cart

=> link_to 'Edit', edit_line_item_path(@line_item)
'|
=< link_to 'Back', line_items_path

app/views/store/index.html.slim
h1 Store#index
p Find me in app/views/store/index.html.slim